### ISSUE TITLE
Some issues about the performance(mIoU)

### ISSUE THREAD

**Issue by ZhiyuXu0124** [YudeWang/SEAM#17]
Hi, 

Thanks for sharing the code.

I am trying to reproduce your code, but the final result I got is 3% different from the result in your article.

I followed the steps in the readme exactly. The results of local training are Train: 63.420%, Val: 60.336%; the results obtained by using the model you provided are: Train: 63.606%, Val: 60.076%.

I am not sure where the problem occurred, and I look forward to your answer, thank you.

**Comment by YudeWang** [comment]
Hi @ZhiyuXu0124 ,

The results are ok, the mIoU of pseudo label is evaluated on train set which is mentioned in section4.3 (63.61%)

The results in Tab.7 is retrained segmentation model prediction on val set. Details can be viewed here: https://github.com/YudeWang/SEAM/issues/11

**Comment by ZhiyuXu0124** [comment]
Ok, I see, thanks for your answer
