### ISSUE TITLE
CUDA error: out of memory

### ISSUE THREAD

**Issue by Eli-YiLi** [YudeWang/SEAM#19]
I CANNOT RUN IT
EVEN USE 8 GPUs (ONE IMG PER GPU)

**Comment by Eli-YiLi** [comment]
THE MATTER IS torch.nn.DataParallel

**Comment by Eli-YiLi** [comment]
--ntasks=1 IN SRUN

**Comment by hyalvin** [comment]
Hi,
I have got the same problem when running the code with an 8*GPU(a100) server, the process just stuck on this line `model = torch.nn.DataParallel(model).cuda()`, so what should I do to solve this?
