### ISSUE TITLE
CRF Inference

### ISSUE THREAD

**Issue by won-bae** [YudeWang/SEAM#2]
Hi, 

Thank you for sharing the code. When I was trying to understand the code, I ran into a trouble to understand crf_inference. In line 96 of infer_SEAM.py, bgcam_score does not seem like probabilities (I checked max value for some images are 1.2). But unary_from_softmax takes probs from softmax as inputs. I am not sure if something is wrong here or I am missing something.
It would be highly appreciated if you could clarify it. Thank you.

**Comment by YudeWang** [comment]
Hi @won-bae , the crf inference code in `infer_SEAM.py` is prepared for the following AffinityNet training and generates foreground/background/undefined three parts. Here the `bg_score` is defined by parameter alpha and `bgcam_score` is not the probability in the strict sense. This part of code comes from the AffinityNet project. And you can combine it with `VOC12AffDataset` in `/voc12/data.py` to understand how it works.

**Comment by won-bae** [comment]
Thank you for the clarification!
