### ISSUE TITLE
The paramters in optimizer

### ISSUE THREAD

**Issue by lzyhha** [YudeWang/SEAM#21]
Hello, I note that the order of paramters (params lr wd) in PolyOptimizer is different from official SGD(params lr momentum). So I think the value of wd will actually be assigned to momentum. Is it so?

```
class PolyOptimizer(torch.optim.SGD):

    def __init__(self, params, lr, weight_decay, max_step, momentum=0.9):
        super().__init__(params, lr, weight_decay)
```

**Comment by YudeWang** [comment]
@lzyhha 
Thanks for your checking. This part of code is borrowed from https://github.com/jiwoon-ahn/psa, and it seems like a small bug which invalidates the momentum. Maybe you can also report this bug to psa repository.

**Comment by lzyhha** [comment]
OK, thank you for your reply:blush:.
