### ISSUE TITLE
What is the pipeline to reproduce the result of Table 6 in your paper?

### ISSUE THREAD

**Issue by Kyfafyd** [YudeWang/SEAM#23]
Thanks for your excellent work and released code.

Looking forward to your reply!

**Comment by YudeWang** [comment]
Hi @Kyfafyd ,
1. Train SEAM network to generate CAM 
2. Train AffinityNet basing on the results of step1 to generate pseudo labels
3.  Train Deeplab model by pseudo labels from step2.

**Comment by Kyfafyd** [comment]
> Hi @Kyfafyd ,
> 
> 1. Train SEAM network to generate CAM
> 2. Train AffinityNet basing on the results of step1 to generate pseudo labels
> 3. Train Deeplab model by pseudo labels from step2.

Thanks very much.
Besides, I wonder what is the pipeline to reproduce the result of Table 6 using your provided pretrained weights?

I just need to do step 3?

**Comment by YudeWang** [comment]
> > Hi @Kyfafyd ,
> > 
> > 1. Train SEAM network to generate CAM
> > 2. Train AffinityNet basing on the results of step1 to generate pseudo labels
> > 3. Train Deeplab model by pseudo labels from step2.
> 
> Thanks very much.
> Besides, I wonder what is the pipeline to reproduce the result of Table 6 using your provided pretrained weights?
> 
> I just need to do step 3?

This repository has provided model weights to generate pseudo labels and you only need to do step 3. And here is some suggestions for step 3: https://github.com/YudeWang/SEAM/issues/11

**Comment by YudeWang** [comment]
Code has release in https://github.com/YudeWang/semantic-segmentation-codebase/tree/main/experiment/seamv1-pseudovoc and I will close this issue.
