### ISSUE TITLE
About training deeplab

### ISSUE THREAD

**Issue by Apexsf** [YudeWang/SEAM#24]
Hi, thank you for your excellent work,  
Can you provide the code of training the fully-supervised deeplab model? Or can you give me some hints about how you initialize the deeplab to train on pseudo labels? Did you just train it from scratch, or use the backbone trained on imagenet, or use the pretrained parameters on coco?
Thank you for your reply.

**Comment by YudeWang** [comment]
Hi @Apexsf ,
Code has released in https://github.com/YudeWang/semantic-segmentation-codebase. Any questions can be given in new repository and I will close this issue.
