### ISSUE TITLE
Performance about `SEAM step`, step3 and `Random walk step`, step3 in README?

### ISSUE THREAD

**Issue by mangoyuan** [YudeWang/SEAM#4]
Thansks for your sharing!
Can you report the mIoU in `SEAM step`, step3 and  `Random walk step`, step3 in README?  
The previous AffinityNet train another segmentation network with pseudo label and the related source code is not open. I am not sure if i can reproduce the results mentioned in AffinityNet becase i am not familiar with the training of DeepLab. Thanks!

**Comment by YudeWang** [comment]
Hi @mangoyuan 
The mIoU of SEAM step, random walk step and deeplab retrained step can be found in the paper. And the paper link has been given in README.
