### ISSUE TITLE
Can you share the segmentation code your used?

### ISSUE THREAD

**Issue by rulixiang** [YudeWang/SEAM#5]
Hey, thanks for sharing your code!
I've run your code and achieved close results as reported on training set. But I didn't find the segmentation code. Can you share it?  
Many thanks!

**Comment by YudeWang** [comment]
Hi @rulixiang ,
There are lots of implementation of DeepLab on github. I think it is easy to choose one and retrain on the pseudo labels generated by SEAM repo. You can also use other advanced segmentation models and do some experiments.
