### ISSUE TITLE
How is CAM mIOU validated?

### ISSUE THREAD

**Issue by LiheYoung** [YudeWang/SEAM#6]
Hi @YudeWang, whether CAM mIOU reported in your paper validated on original PASCAL VOC trainset or SBD augmented trainset? When I use the same hyperparameter as your code, I can only get 43.9% mIOU with single-scale test on augmented trainset, lower than reported 46.1%.

**Comment by YudeWang** [comment]
Hi @LiheYoung ,
The CAM mIoU is validated on original PASCAL VOC trainset with 1464 images. The annotations of SBD augmented dataset is more coarse than pure VOC dataset, especially for bicycle.

**Comment by LiheYoung** [comment]
Thanks for reply! @YudeWang
