### ISSUE TITLE
CAM is not accurate.

### ISSUE THREAD

**Issue by ChrisLee63** [YudeWang/SEAM#8]
Hi, I know the performance of weakly-supervised semantic segmentation is not so well as supervised SS.

But I still confused about the result, it's much worse than I thought.

Original image:
![image](https://user-images.githubusercontent.com/39628662/86355257-fdf78a80-bc9c-11ea-921a-746774e40a4f.png)

CAM:
![image](https://user-images.githubusercontent.com/39628662/86355273-08b21f80-bc9d-11ea-9c27-68084bd937af.png)

I just run this command: `python infer_SEAM.py --weights ../resnet38_SEAM.pth --infer_list voc12/val.txt --out_cam_pred out_cam_pred`

**Comment by JingyiWang2021** [comment]
Hi @serend1p1ty ,

Did you find the answer of your question? 
I am trying to use SEAM to generate CAMs of another dataset, but I don't know how to do it. Do you think that I can make it by just running this command:  ` python infer_SEAM.py --weights ../resnet38_SEAM.pth --infer_list voc12/val.txt --out_cam_pred out_cam_pred` ?
